### ISSUE TITLE
Darkmode improvements & workarounds

### ISSUE THREAD

**Issue by EzioTheDeadPoet** [focustense/easymod#100]
Darkmode has some visibility issues with the default icon (the blue ID icon), that get amplified if you use a night mode like the build in one from windows or an app like f.lux to a point where the icon practically is invisble.

Recoloring that icon might fix it. 

Another nice to have improvement or workaround would be a theme setting to choose between:
- system
- light
- dark

**Comment by focustense** [comment]
Thanks for reporting. In-app theme setting might be quite difficult compared to just fixing the dark mode issues, but I'll give it some thought.

For the record, it's not just the hardcoded blue ID icon that's hard to see, there are also the face/facegen icons that for some reason are not using the default theme color, and are literally invisible - you'll see a tooltip if you hover over the spot they're supposed to be in.

These just need to have correct theme colors.
