### ISSUE TITLE
Damaged BSAs? (Beta 2)

### ISSUE THREAD

**Issue by XLRT** [focustense/easymod#109]
Seems like all BSAs except the first one are damaged. NPC Appearances Merged - Textures.bsa extracts fine but NPC Appearances Merged - Textures0.bsa gives errors for every file in the archive:

textures\actors\character\adelaisa\eyes\eyeinfinity.dds
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.BinaryReader.ReadByte()
   at SharpBSABA2.BSAUtil.BSAFileEntry.WriteDataToStream(Stream stream, Boolean decompress)
   at SharpBSABA2.ArchiveEntry.Extract(String destination, Boolean preserveFolder, String newName)
   at BSA_Browser.Classes.ExtractOperation.Worker_DoWork(Object sender, DoWorkEventArgs e)

**Comment by focustense** [comment]
How big are the failing BSAs?

While I have nothing directly to do with BSA Browser and can think of a few possible reasons why it might try to read past EOF, the most likely one is that EasyNPC never actually finished building the BSAs, i.e. the build failed or the app was shut down while that step was still ongoing. Please post the log file for that session so we can see or rule that out.

EasyNPC only owns the wrapper around the native libbsarch (C/C++ library, same own used by Cathedral Assets Optimizer and not modified a whole lot from original xEdit code), so I don't think it's very likely to be a bug. I'm aware of just one issue in the past where CAO created a broken BSA, and it showed up as one file _inside_ the BSA being impossibly large (over 1 GB). You don't need to extract to see that, you can sort by size in BSA Browser and check if anything looks that large.

So in descending order of probability it's either (a) an interrupted build, (b) an extremely obscure and hard-to-trigger bug in libbsarch, or (c) a defective disk or I/O controller. EasyNPC log file is the place to start looking.

**Comment by XLRT** [comment]
It's fine now, I can't reproduce it anymore so something was preventing finishing the packing process. But I didn't get any error message from EasyNPC so I thought it was a bug.

**Comment by focustense** [comment]
Alright then. If it happens again, let me know. It _shouldn't_ be possible for the app to crash without showing the crash dialog, but if it does, then there should still be a trace in the application event log.
