### ISSUE TITLE
Something went wrong - Analysis Step - System.AggregateException

### ISSUE THREAD

**Issue by kyledws** [focustense/easymod#125]
I get the "Something went wrong" pop up when I enter the plugin analysis step.

Steps to reproduce:
1. Open EasyNPC
2. Confirm all Bethesda plugins are selected
3. Click OK on plugin selection screen
4. See "Something went wrong" popup while plugin analysis is running

Logfile: https://pastebin.com/Xk2qRsZF

I did the steps to reproduce a few times, each time it failed. I then tried them again but I unchecked Dragonborn.esm and I didn't get the pop up. (Dragonborn.esm is mentioned in exception in logfile which is what gave me the idea.) I did clean Dragonborn.esm the other day per Lexy's LOTD guide. Not sure if that's the cause but I figured I'd mention it.

**Comment by focustense** [comment]
This is Mutagen reporting a corrupted plugin. I doubt very much that it's `Dragonborn.esm` (unless you've modified it). The one other plugin I see that is still being analyzed when the error occurs is `Insects Begone - DragonBorn Spiders and Ashoppers.esp`.

Try disabling that insect one and see if it loads.

**Comment by kyledws** [comment]
Disabling the insects plugin fixed the issue. Glad it was so simple. Thanks for your help and the great mod!
