### ISSUE TITLE
Something went wrong crash while building patch

### ISSUE THREAD

**Issue by is33d34dp30pl3** [focustense/easymod#137]
I was building my patch and it crashed during applying facegen data and applying face customizations I have not updated to anniversary edition https://docs.google.com/document/d/1BQGNsqikLwQkUFxR4nMIWPl1vhJJzN5zmE354LhbPKs/edit?usp=sharing
[Log_20211122_211632_7291217.txt](https://github.com/focustense/easymod/files/7585939/Log_20211122_211632_7291217.txt)

**Comment by focustense** [comment]
Hi, just had a look at the report.

It's showing an invalid reference in Bijin AIO - not sure why that's not getting caught on startup, probably there's some path that's included in the build that I forgot to include in the checks.

But more importantly, mods like Bijin AIO are not supported, and this is something that's been documented in a few places - maybe it was more prominent in the old docs and I haven't emphasized it enough in the newer wikis.

Bijin AIO is trying to do the same job that EasyNPC is already doing - merge mods together - but does it dangerously, by not including any of the required assets, and having implicit and untraceable dependencies on the original mods.

So don't use it. To solve this problem, yeet the Bijin AIO mod, restore the original Bijin plugins (I suppose you'll need to update several profile entries if they were pointing to the AIO plugin) and run the build again.

If you run into the same error without using Bijin AIO, please let me know/update the bug. Thanks!
