### ISSUE TITLE
"SkinNaked" applied to WNAM for player character, resulting in invisible beast race bodies

### ISSUE THREAD

**Issue by Dylan-Perry** [focustense/easymod#138]
Recap from focustense on Wabbajack Discord:

> Ok, I might have missed some stuff. This only happens on the PC, and not NPCs? That would make more sense since the PC is by default not a beast race. 
> Probably EasyNPC should just ignore the PC record, it picks it up right now because sometimes there are plugins that decide to modify the PC, and as far as the tool is concerned it's just another NPC in the list. But I assume it should be OK to just delete that record completely from the generated plugin.
> You could remove the WNAM, or just remove the entire record, I doubt it's patching or forwarding anything important.

**Comment by focustense** [comment]
Clarifying here, the issue isn't that there's anything unusual about what's being done to the PC record, but that the PC is being included at all. Although it is technically just another NPC, it needs to go through in-game chargen and therefore it is a bad outcome to have any explicit overrides of this record in the output. Should simply ignore the whole NPC and never include it in profile.

**Comment by focustense** [comment]
For some reason I never duped this. Covered in #133.
