### ISSUE TITLE
Scroll horizontally across mugshots using Shift+Scroll Wheel

### ISSUE THREAD

**Issue by Dylan-Perry** [focustense/easymod#139]
Would be nice for those NPC's with tons of variants <3

**Comment by focustense** [comment]
Yeah, horizontal scrolling can be pretty awful no matter how you slice it. I'll look into it but I'm not sure if there's an easy fix. I'm not using custom UI controls that I built myself, these are all pretty standard WPF widgets and how they scroll is built in. But maybe I can see if it's possible to hook the wheel event and force an explicit scroll.

I don't see why it should require a shift key, just the regular scroll wheel ought to work. I thought it did work, but it clearly doesn't in the current version, maybe it never did.
