### ISSUE TITLE
Add a "jump to" feature 

### ISSUE THREAD

**Issue by TwistedModding** [focustense/easymod#14]
"jump to" right click integration for the "check for problems" section to jump straight to the npc in question where problems are reported would save a lot of time, especially for people with a lot of these(which would be expected on a first run) like me.

**Comment by focustense** [comment]
Agree, though I think double-click is a more intuitive behavior than right-click, and if that's not discoverable enough, I can put a link in the single-click details.

Some warnings are not specific to an NPC, so this would of course only work for the ones that are.

**Comment by TwistedModding** [comment]
I agree on the double click! Also maybe at the same time, add a feature to quickly go back to that page by clicking like mouse 4 or 5. "Some warnings are not specific to an NPC, so this would of course only work for the ones that are." and yes, i was mainly targeting the npc specific problems with this feature, but you understood that anyways.

**Comment by focustense** [comment]
Noting here so that I don't forget later: it may be necessary to remove/suppress active filters on the profile page in order to ensure that the record actually gets selected.
