### ISSUE TITLE
Load order mods matter ?

### ISSUE THREAD

**Issue by KingOmega** [focustense/easymod#142]
Hello to you sorry I'm French I don't speak English well, I have a problem I'm using EasyNPC with several Mods, in this order before the merge:
Pride Of Skyrim, Kalilies, Bijin, Modpocalyps and Pandorable there are almost only the mods of Pride Of Skyrim but I have black face or pink hair with, Brynjolf, Shadr, Brand Shei, Ancano, Maramal etc ...
I think it is not working correctly surely because I didn't choose against the load order but I don't want to use only ONE type of mod for each NPC, can you explain to me how to fix this please ?

**Comment by focustense** [comment]
From the title:

> Load order mods matter ?

Not when creating your profile/build, except with how defaults are chosen on the first run. This is explained on several wiki pages including the [Getting Started](https://github.com/focustense/easymod/wiki/EasyNPC-%E2%80%90-Home#getting-started) guide. It certainly matters _after_ the build, you need to follow instructions and make sure that the original mods are disabled and that the EasyNPC plugin loads last, except for other dynamic patches.

> I don't want to use only ONE type of mod for each NPC

I don't understand the concern here. Of course you can only choose one appearance for each NPC - that seems obvious?

> I have black face or pink hair

Sorry, but I'm unable to support people's individual in-game issues without a detailed report. See [Reporting Bugs: In-Game Issues](https://github.com/focustense/easymod/wiki/Reporting-Bugs#in-game-bugs) on the wiki.
