### ISSUE TITLE
File stuck as Master, even when no NPCs are using defaults from that mod

### ISSUE THREAD

**Issue by Exarielle** [focustense/easymod#147]
![masterdetails](https://user-images.githubusercontent.com/100872761/156648930-9cdfb741-f138-40af-8d75-1105fea464e6.png)
![affectednpcs](https://user-images.githubusercontent.com/100872761/156648939-26ae20cb-ee47-4f0a-a249-4fbb80772e89.png)

For some reason, the mod 'Diversity- A Character Overhaul' isn't cooperating with EasyNPC. The mod in question can be found [here](https://www.nexusmods.com/skyrimspecialedition/mods/5291).
Despite having no NPCs use this particular mod for their 'Default', it is still listed as a Master file. I have tried resetting my profile, trimmed my autosave, and also tried a new profile entirely with a minimal load order active, all with the same result.

**Comment by nickwinker** [comment]
I have the exact same problem. I built the mod and opened it up in sseedit with Diversity in the load order, and cleaned unused masters, and it worked and diversity was removed as a master.

**Comment by focustense** [comment]
Closing as no repro for now. Will look into it if someone provides a clean repro.
