### ISSUE TITLE
(ERROR) Pandorable, Bijin, and KaliliesNPC

### ISSUE THREAD

**Issue by Mungust** [focustense/easymod#148]
[Log_20220410_202938_2832850.txt](https://github.com/focustense/easymod/files/8458993/Log_20220410_202938_2832850.txt)

**Comment by focustense** [comment]
```
2022-04-10 20:48:52.497 +08:00 [01] [ERR] Exception was not handled
Focus.Apps.EasyNpc.Build.BuildException: Task 'Copy Shared Resources' (Focus.Apps.EasyNpc.Build.Pipeline.SharedResourceCopyTask) failed to complete
 ---> System.AggregateException: One or more errors occurred. (There is not enough space on the disk. : 'C:\Users\PC\AppData\Local\ModOrganizer\MO2 - Skyrim Special Edition\mods\NPC Merge 2022-04-10\meshes\KS Hairdo's\SandglassHl.nif')
```

You're out of disk space. Keep in mind that when you generate the merge, you need enough space on disk for all of the loose files *plus* the generated BSAs; the loose files will get deleted after BSAs are built.

For large-ish merges, it's not unusual to require ~30 GB or so for the loose files. I had an idea to allow building directly to BSA without requiring any staging files (#73) but it's low priority.
