### ISSUE TITLE
Windows 11, MO2, Skyrim AE, Hard Crash.

### ISSUE THREAD

**Issue by Painbringer07** [focustense/easymod#151]
Functions fine up until I build the patch.  Gets through copying all assets, patching the mods together, and then 90% through compressing the BSA.  After that my computer locks up, and then hard crashes. Black screen, computer shut down.
I have 16gbs of RAM and a fairly good SSD......  
(How do you find the log files?)

Any Ideas?

Thanks.

**Comment by Painbringer07** [comment]
I noticed that the Event Viewer does not show any app errors in regards to EasyNPC.exe.
It does however show that Explorer.exe crashed, and that Windows.UI.Xaml.dll was the particular thing that caused it.

So my guess would be, No worky with Win. 11.

**Comment by Masamune3210** [comment]
There is literally no way that a user-mode program could cause a BSOD or a hard crash, either you have some funky drivers, your Windows install is royally hosed, or you have some faulty hardware or another hardware issue

**Comment by Painbringer07** [comment]
Well I don't know what to tell you.  I run a B450M MSI MOBO, Corsair RAM, MSI 1660 TI, Samsung SSD, Ryzen 5600X.
I just tried to run the program in Admin and Compatibility mode. Same problem.   It literally almost finishes, just a sliver of the bar left.   It does actually output a file into MO2.  But enabling it gives everyone "Black Face".  I am overclocking if that makes a difference.   There was a bunch of stuff in the Event Viewer about Steam updating, Certificates Expiring, and Anti-Virus activating and updating.  I could try excluding EasyNPC I guess.

**Comment by Painbringer07** [comment]
Masamune3210: "You have some funky drivers"

LOL! Yup, downloaded MSI Center and updated my drivers.  Fixed.

Thanks
