### ISSUE TITLE
Something Went Wrong

### ISSUE THREAD

**Issue by duffer5150** [focustense/easymod#161]
First time I have encountered any issue with Easy NPC.  This is what stood out in the log file.

2022-09-30 02:00:54.438 -04:00 [01] [ERR] Exception was not handled
System.Globalization.CultureNotFoundException: Culture is not supported. (Parameter 'culture')
1033 (0x0409) is an invalid culture identifier.
   at System.Globalization.CultureData.GetCultureData(Int32 culture, Boolean bUseUserOverride)
   at System.Globalization.CultureInfo..ctor(Int32 culture, Boolean useUserOverride)
   at System.Globalization.CultureInfo..ctor(Int32 culture)

Have no idea what this is.  Was going to change the mod being used for Ysolda and this came up.  Disabled an AIO for CC Content NPC's, the esp created for high poly heads through xedit, and RS Children prior to continuing.  Clicked to sort to Ysolda, and the message came up. 

[Log_20220930_015750_5719428.txt](https://github.com/focustense/easymod/files/9681193/Log_20220930_015750_5719428.txt)

**Comment by focustense** [comment]
Unfortunately I don't know what it is either. It seems to be something related to .NET 6, which I assume that you installed at some point in the last few months?

Just to confirm, is it still happening?

**Comment by duffer5150** [comment]
Problem appears to have resolved itself with the last Windows update.  I
was able to search for NPC's by name without issue and am now trying yet
another Lydia replacer.

Thank you for the follow up!!

Regards;

Paul
