### ISSUE TITLE
Arithmetic Overflow Error

### ISSUE THREAD

**Issue by technicallyJack** [focustense/easymod#162]
This is by no means a huge deal. I tested it a bit, and it's due to the side scroll on my Logitech MX Master mouse. Easy NPC is still functional if I don't use the side scroll. I just have to break the habit, haha. I don't even know if you care enough to fix it. Just thought I'd put the report in.

[Log_20221004_221642_8950604.txt](https://github.com/focustense/easymod/files/9712958/Log_20221004_221642_8950604.txt)

**Comment by focustense** [comment]
Yep, that's an odd one, it was discovered a while ago (#135) but I never got around to fixing it since it's pretty rare.

I'll try to get to it sometime soon...
