### ISSUE TITLE
Installed mods coming up as "Not Installed" or "Disabled" and multiple FaceGen not found alerts

### ISSUE THREAD

**Issue by cat210803** [focustense/easymod#167]
![Capture2](https://user-images.githubusercontent.com/109721594/201499246-0a836c32-a357-4868-a3e4-c9fc6ae37578.PNG)
![Capture3](https://user-images.githubusercontent.com/109721594/201499247-de15fa92-d176-44e9-83e6-6d3cf832ff22.PNG)

I am using the latest Nexus version of Easynpc through MO2. None of my npc mods are being recognized and are coming up as disabled or not installed. In the above picture, I have Aela as an example, I have Gman's ladies of Whiterun, Pandorable's shield sisters and bijin warmaidens installed but all of them show up as disabled or not installed.

Additionally, I have and alert from basically all of my npc mods, saying that a FaceGen file was not found. 

Clearly I have done something wrong, how do I fix it?

**Comment by focustense** [comment]
Looks like the mod directory is misconfigured, or wasn't detected correctly. Please post the top lines of the log file (Log tab in the app is fine), and verify that they're pointing to the right directory on your machine.

The directory is almost always detected correctly, but it can be wrong if it's been manually changed, if the mod directory was moved, if the tool is being run for a different edition of the game, etc.

**Comment by cat210803** [comment]
Thanks. I figured out what the problem was. It was actually because I was using a very old version of MO2. After updating it, EasyNPC works fine.

**Comment by focustense** [comment]
Must have been a very old version indeed to have caused that. Thanks for your update.
