### ISSUE TITLE
The app doesn't start (nothing gets displayed)

### ISSUE THREAD

**Issue by ben530916** [focustense/easymod#168]
Crash report from Windows event log:

https://pastebin.com/ydyXbEs7

**Comment by focustense** [comment]
This is a typical missing `plugins.txt` file.

The preferred fix is to start the game once from the Bethesda launcher, which should create the file for you. Mod Organizer does _not_ create the file on its own and it is _not_ sufficient for the file to be in Mod Organizer's profile directories.

If that doesn't work, open an explorer window to `%LocalAppData%\Skyrim Special Edition` and create an empty file named `plugins.txt`. Then you should be able to start the app.

If you're running the GOG version of the game, I've heard that it puts all of these files in a different location, which affects Synthesis and other tools as well - have to wait for a Mutagen fix. A possible workaround would be to take wherever the GOG version actually puts the file and copy it to the above location before running the app.

Thanks for the report with trace included!
