### ISSUE TITLE
EasyNpc not seeing skyrim vr

### ISSUE THREAD

**Issue by yellowjacketsucks** [focustense/easymod#173]
I just started modding skyrim vr and skyrim has been one of my favorite games and easy npc is always a must but this time is been very difficult easy npc cannot find skyrim vr even tho it says on the nexus page im not sure what im doing wrong or if its just not able to work with skyrim vr but its somthing that as a fairly nooby modder is becomeing very hard to not use as i have a great time using easy npc since its so awesome but unfortunately not this time

**Comment by walkswithwolf** [comment]
Did you add the game argument for VR?
https://github.com/focustense/easymod/wiki/EasyNPC-%E2%80%90-Command%E2%80%90Line-Arguments#game-selection

**Comment by focustense** [comment]
Per the comment, VR requires a command-line argument. If you're positive that you've set it up correctly and it's still not running, then please provide clearer details and/or a log.

https://github.com/focustense/easymod/wiki/Reporting-Bugs#app-crashes
