### ISSUE TITLE
Crash during Build Process

### ISSUE THREAD

**Issue by DragonBlade117** [focustense/easymod#174]
[Log_20230112_142807_0445061.txt](https://github.com/focustense/easymod/files/10405425/Log_20230112_142807_0445061.txt)
[Log_20230112_142005_1910612.txt](https://github.com/focustense/easymod/files/10405426/Log_20230112_142005_1910612.txt)
[Log_20230112_142501_2662018.txt](https://github.com/focustense/easymod/files/10405427/Log_20230112_142501_2662018.txt)
Program errors out during the FaceGen process. The only error shown has to do with Silah, but it is just saying she is added by a skin-changing mod and the main mod.

**Comment by DragonBlade117** [comment]
[Log_20230113_111801_1151294.txt](https://github.com/focustense/easymod/files/10413354/Log_20230113_111801_1151294.txt)
[Log_20230113_111537_6037006.txt](https://github.com/focustense/easymod/files/10413355/Log_20230113_111537_6037006.txt)
[Log_20230113_111658_9156469.txt](https://github.com/focustense/easymod/files/10413356/Log_20230113_111658_9156469.txt)
New logs, I seem to have sorted teh face gen issue, but now it errors out on the application of them. Keeps getting stuck on Ennis, and a barkeeper.

**Comment by focustense** [comment]
It's the usual error for this sort of thing:

> (BOD2 type not expected on versions < 43)

In other words, you have an LE mod that's been improperly converted to SE. Someone changed the form version without actually upgrading the plugin in Creation Kit. EasyNPC would normally be warning you about this on startup.

Anyway, find out which mod it is and either remove it from load order/profile or fix the conversion.
