### ISSUE TITLE
Vanilla Face Presets winning over EasyNPC

### ISSUE THREAD

**Issue by enragedbard** [focustense/easymod#179]
Not sure how this is even possible, since it's in slot 1 (Skyrim.esm), but after I do a Merge build with EasyNPC and disable all the appearance mods, I run the post-build and it says Vanilla wins with almost every NPC the build touched.  I go into the game and people either have vanilla appearance and hair or potato-head.

I can't exactly disable Skyrim.esm or extract the bsas that came packaged with the game.  How would this even happen?

  
![Vanilla](https://user-images.githubusercontent.com/109352488/222285861-17f17b63-44b8-4280-8e4a-512464684d81.jpg)

**Comment by focustense** [comment]
Not a bug.

https://github.com/focustense/easymod/wiki/EasyNPC-FAQ-&-Troubleshooting#why-is-the-post-build-checker-showing-a-conflict-with-vanilla
