### ISSUE TITLE
Get a "something went wrong" issue every launch. I previously had to go to version 0.9.2 or something to get it to work. Attached are logs from today, last one I had several mods unchecked in the easyNPC interface

### ISSUE THREAD

**Issue by domolords** [focustense/easymod#191]
See attachments
[Log_20231205_133729_5049972.txt](https://github.com/focustense/easymod/files/13572119/Log_20231205_133729_5049972.txt)
[Log_20231205_135514_4651933.txt](https://github.com/focustense/easymod/files/13572120/Log_20231205_135514_4651933.txt)
[Log_20231205_135836_0680916.txt](https://github.com/focustense/easymod/files/13572121/Log_20231205_135836_0680916.txt)
[Log_20231205_141614_9225275.txt](https://github.com/focustense/easymod/files/13572122/Log_20231205_141614_9225275.txt)

**Comment by domolords** [comment]
Both logs from version 0.9.2 just to see if an older version works. (it does not)
[Log_20231205_145521_1772257.txt](https://github.com/focustense/easymod/files/13572407/Log_20231205_145521_1772257.txt)
[Log_20231205_145631_4772456.txt](https://github.com/focustense/easymod/files/13572408/Log_20231205_145631_4772456.txt)

**Comment by focustense** [comment]
Going back to an old version, especially version 0.9.2, was not a good choice, particularly if you tried to import an exported profile which it appears was done. That version had a known profile corruption bug, #103.

People are welcome to use the old versions if they choose, but I offer no support. The official fix for profile corruption is (using a recent version), as documented in more detail in #103, is to delete the `profile.log` file and re-import whatever save file led to the corruption in the first place.
