### ISSUE TITLE
 Javafml:48, server crash on start up

### ISSUE THREAD

**Issue by euquinox** [focustense/easymod#198]
hi! the server is crashing on start up after updating to the latest version of the mod 
is it conflicting with another mod? I can't quite tell

[crash-2024-03-14_16.25.20-fml.txt](https://github.com/focustense/easymod/files/14617611/crash-2024-03-14_16.25.20-fml.txt)

**Comment by focustense** [comment]
This is a Minecraft crash report which has nothing to do with this app or repo.
