### ISSUE TITLE
Error with building with KaliliesNPCs.esp and others

### ISSUE THREAD

**Issue by bookdragon143** [focustense/easymod#206]
[Log_20241006_191437_4100169.txt](https://github.com/user-attachments/files/17272207/Log_20241006_191437_4100169.txt)
Hi, I'm getting this error when trying to build for the first time. Any thoughts?

**Comment by focustense** [comment]
```
 ---> RecordException KaliliesNPCs.esp => 0022F5:KaliliesNPCs.esp<Armor>: Could not resolve record    at Mutagen.Bethesda.IFormLinkExt.Resolve[TMajor](IFormLinkGetter`1 link, ILinkCache cache)
```

As the error says (and provides the form ID), there's an invalid reference in that plugin + record. Usually it's a result having an incompatible version of an upstream mod. I usually suggest opening the mod(s) up in xEdit to try to get more context and detail about what's wrong.

At a minimum, it should let you know which NPCs are invalid so you can pick a different plugin for those. Or fix it by upgrading or downgrading one of the incompatible mods.
