### ISSUE TITLE
EasyNPC "BOD2 type not expected on version < 43" error includes Skyrim.esp but I'm already on 1.6.1170.0 AE

### ISSUE THREAD

**Issue by Vylesh** [focustense/easymod#207]
![resim](https://github.com/user-attachments/assets/c4931618-e778-4c21-bc41-adadcf82d64f)
I'm already on Lastest AE version But EasyNPC is not accepting 
Lastest Log :
[Log_20241015_124800_4293982.txt](https://github.com/user-attachments/files/17376172/Log_20241015_124800_4293982.txt)
My Load Order.
# This file was automatically generated by Mod Organizer.
Skyrim.esm
Update.esm
Dawnguard.esm
HearthFires.esm
Dragonborn.esm
ccasvsse001-almsivi.esm
ccbgssse001-fish.esm
ccbgssse002-exoticarrows.esl
ccbgssse003-zombies.esl
ccbgssse004-ruinsedge.esl
ccbgssse005-goldbrand.esl
ccbgssse006-stendarshammer.esl
ccbgssse007-chrysamere.esl
ccbgssse010-petdwarvenarmoredmudcrab.esl
ccbgssse011-hrsarmrelvn.esl
ccbgssse012-hrsarmrstl.esl
ccbgssse014-spellpack01.esl
ccbgssse019-staffofsheogorath.esl
ccbgssse020-graycowl.esl
ccbgssse021-lordsmail.esl
ccmtysse001-knightsofthenine.esl
ccqdrsse001-survivalmode.esl
cctwbsse001-puzzledungeon.esm
cceejsse001-hstead.esm
ccqdrsse002-firewood.esl
ccbgssse018-shadowrend.esl
ccbgssse035-petnhound.esl
ccfsvsse001-backpacks.esl
cceejsse002-tower.esl
ccedhsse001-norjewel.esl
ccvsvsse002-pets.esl
ccbgssse037-curios.esl
ccbgssse034-mntuni.esl
ccbgssse045-hasedoki.esl
ccbgssse008-wraithguard.esl
ccbgssse036-petbwolf.esl
ccffbsse001-imperialdragon.esl
ccmtysse002-ve.esl
ccbgssse043-crosselv.esl
ccvsvsse001-winter.esl
cceejsse003-hollow.esl
ccbgssse016-umbra.esm
ccbgssse031-advcyrus.esm
ccbgssse038-bowofshadows.esl
ccbgssse040-advobgobs.esl
ccbgssse050-ba_daedric.esl
ccbgssse052-ba_iron.esl
ccbgssse054-ba_orcish.esl
ccbgssse058-ba_steel.esl
ccbgssse059-ba_dragonplate.esl
ccbgssse061-ba_dwarven.esl
ccpewsse002-armsofchaos.esl
ccbgssse041-netchleather.esl
ccedhsse002-splkntset.esl
ccbgssse064-ba_elven.esl
ccbgssse063-ba_ebony.esl
ccbgssse062-ba_dwarvenmail.esl
ccbgssse060-ba_dragonscale.esl
ccbgssse056-ba_silver.esl
ccbgssse055-ba_orcishscaled.esl
ccbgssse053-ba_leather.esl
ccbgssse051-ba_daedricmail.esl
ccbgssse057-ba_stalhrim.esl
ccbgssse066-staves.esl
ccbgssse067-daedinv.esm
ccbgssse068-bloodfall.esl
ccbgssse069-contest.esl
ccvsvsse003-necroarts.esl
ccvsvsse004-beafarmer.esl
ccbgssse025-advdsgs.esm
ccffbsse002-crossbowpack.esl
ccbgssse013-dawnfang.esl
ccrmssse001-necrohouse.esl
ccedhsse003-redguard.esl
cceejsse004-hall.esl
cceejsse005-cave.esm
cckrtsse001_altar.esl
cccbhsse001-gaunt.esl
ccafdsse001-dwesanctuary.esm
_ResourcePack.esl
unofficial skyrim special edition patch.esp
Skyrim Project Optimization - Full Version.esm
unofficial skyrim creation club content patch.esl
Treescale.esm
MajesticMountains_Landscape.esm
Lanterns Of Skyrim II.esm
LegacyoftheDragonborn.esm
3DNPC.esp
MajesticMountains_Moss.esp
Skyrim Extended Cut - Saints and Seducers.esp
BSAssets.esm
BSHeartland.esm
BS_DLC_patch.esp
OCF.esp
Campfire.esm
UHDAP - en0.esp
Better Dynamic Snow SE - DisableRefs.esm
UHDAP - MusicHQ.esp
UHDAP - en3.esp
UHDAP - en2.esp
Lux - Master plugin.esm
Schlongs of Skyrim - Core.esm
SexLab.esm
SexLabAroused.esm
Devious Devices - Assets.esm
Devious Devices - Integration.esm
Phenderix Magic World.esm
Emfy Cleric Robes.esl
Lux - Resources.esp
AncientBloodII.esl
Lux Via.esp
OCPA.esl
Icebloom.esl
Tamrielic Distribution.esp
RaceCompatibility.esm
ZaZAnimationPack.esm
SCSI-ACTbfco-Main.esp
UHDAP - en1.esp
High Poly Head.esm
TrueHUD.esl
Experience.esl
Expressive Facegen Morphs.esl
skymojibase.esl
UHDAP - en4.esp
SmoothCam.esl
Heels Sound.esm
StormCalling.esl
Sotteta Huntress Armor.esl
Crimson Blood Armor.esl
AncientDraugr.esl
Tembtra Thief Armor.esl
Black Widow Outfit.esl
DX Morenn Outfit.esl
Cassandra Apocrypha UNP.esl
Cassandra Frost Witch.esl
DX Witcher Armor.esl
Gwelda Witch.esl
Gwelda Red Riding Hood.esl
WildHuntress.esl
DX Daughter of the Sea.esl
DX Druid Armor.esl
Celes Nightingale Armor.esl
DX Necromancer Robes.esl
Celes Mercy.esl
Celes Rogue Armor UNP.esl
Celes Tarot Outfit Cloth UNP.esl
Daedric Reaper Armor.esl
Demon Armor.esl
DX Christmas Bunny Outfit.esl
DX Dark Knight Armor.esl
DX Succubus Armor.esl
DX Witch Hunter Armor.esl
Gwelda Dawnguard Armor.esl
Gwelda Vampire.esl
Sotteta Necromancer Outfit.esl
Merta Assassin Armor.esl
Merta Black Rose Armor.esl
Spartan Bard Outfit.esl
Stella Mithril Armor.esl
Ursine Armor Pack.esl
Devious Devices - Expansion.esm
Devious Devices - Contraptions.esm
SexLab - Sexual Fame [SLSF].esm
SexLab Attraction.esm
CreatureFramework.esm
W3S.esl
DynDOLOD.esm
Growl - Werebeasts of Skyrim.esp
Particle Patch for ENB.esp
SkyUI_SE.esp
Prometheus_No_snow_Under_the_roof.esp
SMIM-SE-Merged-All.esp
Better Dynamic Snow SE.esp
NSUTR_bugfixes.esp
Audio Overhaul Skyrim.esp
Mortal Enemies.esp
Weapons Armor Clothing & Clutter Fixes.esp
Relationship Dialogue Overhaul.esp
Embers XD.esp
Embers XD - Patch - Lanterns of Skyrim II.esp
Verdant - A Skyrim Grass Plugin SSE Version.esp
LegacyoftheDragonborn0.esp
S3DTrees NextGenerationForests.esp
3DNPC0.esp
BluePalaceTerrace.esp
JK's Blue Palace.esp
JK's Blue Palace Terrace.esp
BluePalaceTerrace-JKsBluePalace-Patch.esp
castle volkihar rebuilt.esp
cutting room floor.esp
CollegeOfWinterholdImmersive.esp
JKs Skyrim.esp
Landscape Fixes For Grass Mods.esp
Folkvangr - Grass and Landscape Overhaul.esp
Immersive Jewelry.esp
AI Overhaul.esp
Skyrim Immersive Creatures Special Edition.esp
SoundsofSkyrimComplete.esp
MysticismMagic.esp
NAT-ENB.esp
HappyLittleTrees.esp
Lux Via - plugin.esp
JK's The Bards College.esp
Helgen Reborn.esp
At Your Own Pace - Thieves Guild.esp
LoS II - JKs Skyrim patch.esp
MilkModNEW.esp
MilkMod_MilkPumpsFancy.esp
SeranaDialogAddon.esp
WACCF_Armor and Clothing Extension.esp
DBM_BluePalaceTerrace_Patch.esp
Hothtrooper44_ArmorCompilation.esp
Realm of Lorkhan - Custom Alternate Start - Choose your own adventure.esp
Pilgrim.esp
NewArmoury.esp
At Your Own Pace - Companions.esp
Skyrim Flora Overhaul.esp
MajesticMountains.esp
JK's Dragonsreach.esp
MoreNastyCritters.esp
HentaiCreatures.esp
SexLab More Creatures.esp
Mists of Tamriel.esp
MilkModNEWJKSkyrimPatch.esp
BluePalaceTerrace-LegacyOfTheDragonborn-Patch.esp
TheChoiceIsYours.esp
Immersive Weapons.esp
Immersive Weapons_WACCF_Patch.esp
PrvtI_HeavyArmory.esp
Wintersun - Faiths of Skyrim.esp
SkyrimSewers.esp
TrueDirectionalMovement.esp
EldenSkyrim.esp
EldenSkyrim_RimSkills.esp
Fenrir.esp
JKs Skyrim_No Snow Under the Roof_Patch.esp
JKs Skyrim - AI Overhaul Patch.esp
WPF - JK Skyrim patch.esp
DBM_HelgenReborn_Patch.esp
KhajiitPaw.esp
JKs BPT - JKs Skyrim patch.esp
Tamrielic Distribution - Dead Man's Dread.esp
BluePalaceTerrace-JKs Skyrim-Patch.esp
SexLabSkoomaWhore.esp
bac.esp
At Your Own Pace - College of Winterhold.esp
SPERG-SSE.esp
LoS II - Lantern Workers.esp
Colorful_Magic_SE.esp
ECSS - Staff of Sheogorath Patch.esp
PrvtI_HeavyArmory_WACCF_Patch.esp
PrvtI_HeavyArmory_AnimatedArmoury_Patch.esp
Haze Lights.esp
Crossbow Integration.esp
Tamrielic Distribution - Vigil Enforcer Armor.esp
Tamrielic Distribution - Crossbow Collection.esp
At Your Own Pace - Dawnguard.esp
Tamrielic Distribution - BS Cyrodiil.esp
PAN_NPCs.esp
ICOW - AIO Patch.esp
Landscape For Grass Mods JK'S Skyrim.esp
DBM_IW_Patch.esp
LoS II - CRF patch.esp
DealingwithBackstories.esp
Embers XD - Patch - JKs Skyrim & LOS2.esp
PAN_NPCs_Males2.esp
DiverseWerewolvesCollection.esp
Immersive Patrols II.esp
ICOW Unofficial Patch.esp
JKs Skyrim - Fishing patch.esp
Drinking Fountains of Skyrim for SSE.esp
DBM_JKSkyrim_Patch.esp
ECSS - Shadowrend Patch.esp
SunHelmSurvival.esp
Convenient Horses.esp
ICOW - JKs Skyrim Patch.esp
JKs Skyrim_Cutting Room Floor_Patch.esp
DBM_CRF_Patch.esp
ICOW - WACCF Patch.esp
DBM_Wintersun_Patch.esp
DBM_ImmersiveCollegeofWinterhold_Patch.esp
Landscape Fixes For Grass mods - Cutting Room Floor Locations.esp
MF_RadiantProstitution.esp
ICOW - 3DNPC Patch.esp
No Snow Under The Roof - CRF Patch.esp
LoS II - 3DNPC addon.esp
the paarthurnax dilemma.esp
JKs BPT - AI Overhaul patch.esp
DBM_S3DTrees_Patch.esp
JKs BPT - LOTD patch.esp
Landscape For Grass mods - Helgen Reborn Patch.esp
Embers XD - Patch - Lux Via.esp
ICOW - LoS II Patch.esp
Vampirelordroyal.esp
AI Overhaul - Cutting Room Floor Patch.esp
3DNPC - AI Overhaul Patch.esp
BluePalaceTerrace-AI Overhaul-patch.esp
LoS II - LotD patch.esp
JKs BPT - AYOP TG patch.esp
DBM_JKBluePalace_Patch.esp
BluePalaceTerrace-LOTD-JKsBluePalace-Patch.esp
BluePalaceTerrace-SkyrimSewers-patch.esp
DBM_IA_Patch.esp
CowLifeServices.esp
DBM_SkyrimSewers_Patch.esp
LoS II - SMIM patch.esp
LoS II - USSEP patch.esp
ICOW - CC - Wild Horses Patch.esp
ForgottenMagic_Redone.esp
MeekoReborn.esp
Apocalypse - Magic of Skyrim.esp
Reverb Interior Sounds Expansion.esp
AcousticTemplateFixes.esp
RimImpactOfMob.esp
PAN_NPCs_Males.esp
RimImpactOfPlayer.esp
P1FlyingRing.esp
CC-FearsomeFists_WACCF_Patch.esp
DBM_WACCF_Patch.esp
DBM_ImmersiveJewelry_Patch.esp
Animated Wings Ultimate.esp
SPERG_ApocalypsePatch.esp
At Your Own Pace - Main Quest.esp
Dovabear.esp
EggFactory.esp
Embers XD - Patch - JKs Dragonsreach.esp
DBM_JKDragonsreach_Patch.esp
Amaterasu - The Great Spirit.esp
Adamant.esp
JKs BPT - Skyrim Sewers patch.esp
JKs BPT - ICoW patch.esp
JKs BPT - 3DNPC patch.esp
RaceMenu.esp
RaceMenuPlugin.esp
SOSRaceMenu.esp
3BBB.esp
CBBE.esp
RaceMenuMorphsCBBE.esp
MCMHelper.esp
At Your Own Pace - Dark Brotherhood.esp
At Your Own Pace - Misc.esp
Keytrace.esp
1nivWICCloaks.esp
WACCF_Armor and Clothing Extension_SPID.esp
AI Overhaul - RDO Updated Patch.esp
VioLens SE.esp
Attack_MCO.esp
SoS_NATENB_Patch.esp
EldenWarAshForMCO.esp
EldenWarAshPack1.esp
EldenWarAshPack2.esp
KeyTraceForEldenRim.esp
SCSI-BfcoEldenPatch.esp
UltimateCombat.esp
Odin - Skyrim Magic Overhaul.esp
ENB Light.esp
Embers XD - Patch - Legacy of the Dragonborn.esp
Embers XD - Patch - Goldenhills Plantation.esp
Embers XD - Fire Magick Add-On.esp
JKs BPT - ACE patch.esp
DBM_HA_Patch.esp
Lux Via - Blended Roads Bridges Texture sets.esp
Lux Via - Animated Container Snow shader fix.esp
CC-NecromanticGrimoire_WACCF_Patch.esp
CC-Fishing_WACCF_Patch.esp
CuttingRoomFloor_WACCF_Patch.esp
DBM_SMIM_Patch.esp
LoS II - Campfire addon.esp
LoS II - Sounds of Skyrim patch.esp
3DNPC - CRF Patch.esp
3DNPC1.esp
Reverb Interior Sounds Expansion_VolumeSlider_Rain.esp
Reverb Interior Sounds Expansion_VolumeSlider_Thunder.esp
SunDaytimeSouth.esp
Seasons of Bruma.esp
LoS II - Bruma patch.esp
Bruma Lighting Compatibility Patch.esp
Embers XD - Patch - Beyond Skyrim - Bruma.esp
CWICRFSEPatch.esp
ICOW - ACE Patch.esp
JKs Skyrim - Gray Cowl Patch.esp
ICOW_GrayCowlCC_Patch.esp
CWISPOPatchSE.esp
Schlongs of Skyrim.esp
BadDogSchlongCore.esp
LoS II - HelgenReborn patch.esp
StopOnSlash.esp
EldenParry.esp
EldenCounter.esp
UntarnishedUI_Subtitle.esp
EmbersXD-Campfire Patch.esp
BetterThirdPersonSelection.esp
I4IconAddon.esp
AHZmoreHUD.esp
EWM_SunhelmSurvivalSE.esp
SunHelmCampfireSkill.esp
SunHelmDiseases.esp
SunHelm_3DNPC.esp
Experience Quests Tweak.esp
QuickLootIE.esp
BlendedRoads.esp
Yggdrasil Music.esp
ECSS - Beyond Skyrim Music Patch.esp
ECSS - Ruin's Edge Patch.esp
SPERG_USSEPPatch.esp
PilgrimCyrodiilPatch.esp
dD - Enhanced Blood Main.esp
EBT - IC PATCH.esp
AcousticTemplateFixes_CC_Farming.esp
AcousticTemplateFixes_CC_Seducers_EC.esp
AcousticTemplateFixes_ReverbInteriorSounds.esp
AOS_EBT Patch.esp
SkyHUD.esp
PAN_MarvellousMiners.esp
PAN_LethalLadies.esp
PAN_Nevri.esp
PAN_Initiates.esp
PAN_BlackBriar.esp
PAN_Brelyna.esp
PAN_DashingDefenders.esp
PAN_DunmerDamsels.esp
PAN_NPCs_DB.esp
PAN_NPCs_DG.esp
PAN_Shieldsisters.esp
PAN_Sovngarde.esp
Trueblood Serana.esp
Pureblood Valerica.esp
PAN_Valerica.esp
PAN_WarriorWomen.esp
Wintersun - SIC Patch.esp
UIExtensions.esp
SDA CC Umbra Patch.esp
SDA RDO Patch.esp
SDA_SpellToggleExtendedV2.esp
Race Compatiblity - Serana Add-on Dialogue.esp
SDA Campfire Patch.esp
SDA Serana Cure Quest Plus Patch.esp
OBody.esp
KS Hairdo's.esp
SnowOverSkyrim.esp
Chesko_WearableLantern.esp
Smoking Torches And Candles.esp
Dynamic Activation Key.esp
Hothtrooper44_Armor_Ecksstra.esp
Hothtrooper44_ArmorCompilation_WACCF_Patch.esp
SPERG_ImmersiveArmorsPatch.esp
ImGladYoureHere.esp
SDA GYH Patch.esp
skymoji.esp
empitificator.esp
TCIYMErger.esp
CC-Bittercup_TCIY_Patch.esp
CC-BloodchillManor_TCIY_Patch.esp
CC-BoneWolf_TCIY_Patch.esp
CC-DeadMansDread_TCIY_Patch.esp
CC-HeadmansCleaver_TCIY_Patch.esp
CC-Hendraheim_TCIY_Patch.esp
CC-LordsMail_TCIY_Patch.esp
CC-PlagueOfTheDead_TCIY_Patch.esp
CC-StaffOfSheogorath_TCIY_Patch.esp
CC-Sunder&Wraithguard_TCIY_Patch.esp
CC-TheContest_TCIY_Patch.esp
CC-VigilEnforcer_TCIY_Patch.esp
SIC WACCF Patch.esp
BCS_TCIY_Patch.esp
TCIY_Wintersun_Patch.esp
RareCuriosBoltsExpanded.esp
Crossbow Integration - Rare Curios Bolts.esp
Crossbow Integration - Rare Curios Bolts Expanded.esp
Crossbow Integration - Expanded Crossbow Pack.esp
PrvtI_HeavyArmory_AA_WACCF_Patch.esp
Crossbow Integration - Expanded Crossbow Pack Orcish Extension CRF.esp
SIC ACE Patch.esp
Saints&SeducersExtendedCut_WACCF.esp
TCIY_CRF_Patch.esp
RaceCompatibilityUSKPOverride.esp
LustmordVampireArmor.esp
SDA Lustmord Patch.esp
TGNoToNocturnal.esp
SDA No To Nocturnal Patch.esp
DBM_Adamant_Patch.esp
DBM_NoToNocturnal_Patch.esp
Heavy Armory - Immersive Jewelry.esp
Prvti_HA_Fishing_DraugrWeapons_WACCF.esp
PrvtI_HeavyArmory_ExpandedCrossbowPack_Patch.esp
PrvtI_HeavyArmory_RareCurios_Patch.esp
PrvtI_HeavyArmory_USSEP_Patch.esp
AnimatedHeavyArmoury.esp
Animated Immersive Weaps.esp
Crossbow Integration - Elite Crossbows.esp
Tamrielic Distribution - Rare Curios.esp
Tamrielic Distribution - AA Elven Hunter.esp
Tamrielic Distribution - AA Leather.esp
Tamrielic Distribution - Netch Leather Armor.esp
Tamrielic Distribution - AA Iron.esp
Tamrielic Distribution - AA Silver.esp
Tamrielic Distribution - AA Steel Soldier.esp
Tamrielic Distribution - AA Ebony Plate.esp
PrvtI_HeavyArmory_CrossbowIntegration_CC-ECP_Patch.esp
PrvtI_HeavyArmory_CrossbowIntegration_CC-RC_Patch.esp
PrvtI_HeavyArmory_TD-CrossbowCollection_Patch.esp
PrvtI_HeavyArmory_TD-CrossbowCollection_AA_Patch.esp
PrvtI_HeavyArmory_CrossbowIntegration_AA_Patch.esp
Pan NPCs - Immersive Jewelry.esp
AIO SE TATTOOS.esp
CommunityOverlays3.esp
ZMDs Feet Nail Art for RaceMenu v1.esp
High Poly Pretty Face and Darker Brows Stand Alone.esp
High Poly Head Vampire Fix.esp
AI Overhaul - PAN_NPCs_DG Patch.esp
IA CBBE Patch.esp
TW3Eyes.esp
FSMPM - The FSMP MCM.esp
Xing SMP Hairs and Wigs - Dint999.esp
Xing SMP Hairs and Wigs - Fuse.esp
Xing SMP Hairs and Wigs - HHairstyles.esp
SOS - Smurf Average Addon.esp
HIMBO.esp
RaceMenuMorphsHIMBO.esp
ED Horns SSE.esp
ED Horns RMIntegration.esp
Brows.esp
Kyoe BanginBrows.esp
Maevan2EyeBrows.esp
GoamElvenEars.esp
GoamElvenEarsRMIntegration.esp
Maevan2 Eye Brows for High Poly Head.esp
Brows for High Poly Head.esp
TheEyesOfBeauty.esp
The Eyes Of Beauty - Elves Edition.esp
FMS_FemaleMakeupSuite.esp
Improved Eyes Skyrim.esp
MikanEyes All in one SE.esp
VWA_VanillaWarpaintsAbsolution.esp
Pocky Punk's Make Up Addon_females.esp
AddItemMenuSE.esp
GR Inari EarsTails SMP.esp
InariTail_RM_2-3.esp
[Tec] GR Inari EarsTails SMP.esp
Celtic Music in Skyrim - Combat.esp
Celtic_Music_In_Skyrim_SE.esp
Celtic_Music_In_Skyrim_SE_Dungeon.esp
Convenient Horses Anniversary Edition Patch.esp
zz_HorseOverhaul.esp
ZZHorsesandWHPatchbyDudel.esp
Fluffworks.esp
THMeeko.esp
Moonlight Tales Mini.esp
MCU_Examples.esp
CarryWeight x100.esp
WiZkiD Imperial Forts.esp
Simplicity of Snow - BSBruma Patch.esp
Simplicity of Snow.esp
Simplicity of Snow - Dwemer Sanctuary Patch.esp
Ghosu - Auriel.esp
Praedy's AncientFalmerThrone.esp
Praedy's MageStatueFX.esp
Praedy's WinterholdCollegeBanner.esp
XPMSE.esp
Embers XD - Patch - SunHelm Survival.esp
ImmersiveCheatMenu.esp
[Orimagen]GoamEarrings.esp
NosPiercedEarsAll.esp
Precision.esp
SDA Convenient Horses Patch.esp
IA_CBBE.esp
Immersive Armors Weight Patch.esp
Nordic Ruins Sulfur Parallax.esp
Skyrim Remastered - Ice Caves Fix.esp
ObiTattoos.esp
BRB_BeastRaceBodypaints.esp
EvenMoreMakeup.esp
Cassandra Frost Witch.esp
Gwelda Dawnguard Armor.esp
Celes Nightingale Armor.esp
[QH]Yingye.esp
[Odd] Demon Seducer.esp
Moonlight Tales - Fluffworks - Real beasts.esp
Pan NPCs DB - Diverse Werewolves Collection.esp
Moonlight Tales Mini - MCM.esp
DX Succubus Armor.esp
Celes Rogue Armor UNP.esp
Crimson Blood Armor.esp
Cassandra Apocrypha UNP.esp
DX Dark Knight Armor.esp
Celes Mercy.esp
Demon Armor.esp
DX Necromancer Robes.esp
DX Witch Hunter Armor.esp
Spartan Bard Outfit.esp
Stella Mithril Armor.esp
SandboxWhenIdle.esp
Ursine Armor Pack.esp
Sotteta Necromancer Outfit.esp
Daedric Reaper Armor.esp
DX Witcher Armor.esp
PuppetMaster.esp
Gwelda Red Riding Hood.esp
Gwelda Witch.esp
Tembtra Thief Armor.esp
WildHuntress.esp
ValhallaCombat.esp
EnhancedAtronachs.esp
bkspell.esp
DBVO.esp
NB-Scars.esp
AFB_ScarSliderHP.esp
TW3Weaponry.esp
Werewolf Killcam Remover.esp
Phenderix Elements.esp
Apocalypse - More Apocalypse.esp
Elemental Destruction Magic Redux.esp
KSHairdosSMP.esp
KSWigsSMP.esp
Growl-MortalEnemies Patch.esp
CiriOutfit.esp
SOS - TRX - Futanari Addon.esp
SOS - TRX - Futanari Addon Canine.esp
SOS - TRX - Futanari Addon Horse.esp
Sexcraft.esp
SLAnimLoader.esp
OSLAroused.esp
OAroused.esp
NoOverpenetration.esp
Devious Devices SE patch.esp
dse-soulgem-oven.esp
AnubAnimObj.esp
sr_FillHerUp.esp
PregnancyNormalmapSwapper.esp
OninusLactis.esp
Sgo4 Integration Fork.esp
SexLab Inflation Framework.esp
FNIS.esp
FNISspells.esp
12FemaleBrows.esp
SOS - ERF - Horse Penis Redux Addon.esp
SOS - ERF - Horse Penis Redux Addon (No Balls).esp
WetFunction.esp
MNCWereHermPlayer.esp
Convenient Horses MNCPatch.esp
MilkModNEW HF.esp
MilkModNEW CF.esp
MilkModNEW Sanbox.esp
MilkModNEW ZaZ Sanbox.esp
Jugs.esp
Footprints.esp
Footprints - ENB.esp
BDSpikySlitSchlong.esp
BDHoodieSchlong.esp
YASeducerSchlong.esp
SLSO.esp
SexLab TDF Aggressive Prostitution.esp
SexLabDefeat.esp
Being a Cow Tats.esp
SDA Castle Volkihar Rebuilt Patch.esp
Castle Volkihar Rebuilt - RDO Patch.esp
PrvtI_HeavyArmory_CrossbowIntegration_RCBE_Patch.esp
PrvtI_HeavyArmory_RareCuriosBoltsExpanded_Patch.esp
Crossbow Integration - Complete Bolts Expanded.esp
Conditional Expressions.esp
EasyWheel2 SSE.esp
run for your lives.esp
Take A Peek - New Stealth Mechanic.esp
KvSweets.esp
SDA Sweets and Such Patch.esp
Dr_Bandolier.esp
Palaces Castles Enhanced.esp
JKs Blue Palace - PCE Patch.esp
Jk Dragonsreach Castle Enhanced patch.esp
PCE - USSEP+CRF Patch.esp
PCE - SPO Patch.esp
PCE - AI Overhaul Patch.esp
DBM_PCE_Patch.esp
JKs Blue Palace - PCE - JKs Skyrim - LOTD Patch.esp
PCE - 3DNPC Patch.esp
PCE - RDO Patch.esp
PCE - Skyrim Sewers Patch.esp
PCE - ICOW Patch.esp
JKs Blue Palace - PCE - 3DNPC Patch.esp
JKs Blue Palace - PCE - AI Overhaul Patch.esp
Trade & Barter.esp
Adamant_T&B_Patch.esp
DBM_TradeBarter_Patch.esp
Complete Alchemy & Cooking Overhaul.esp
CACO_Beyond Skyrim Bruma_Patch.esp
CACO_Survival Mode_USSEP_Patch.esp
CC-Fishing_CACO_Patch.esp
CACO_SkyrimImmersiveCreaturesSE_Patch.esp
CACO_SPERG_Patch.esp
JKs BPT - CACO patch.esp
CC-Bittercup_CACO_Patch.esp
CC-PlagueOfTheDead_CACO_Patch.esp
CC-BowOfShadows_CACO_Patch.esp
DBM_CACO_Patch.esp
CACO Rare Curios Patch.esp
Saints&SeducersExtendedCut_CACO.esp
CC-ForgottenSeasons_CACO_Patch.esp
CC-BloodchillManor_CACO_Patch.esp
CACO_Bruma_Rare Curios_Patch.esp
CACO Curios Patch.esp
CC-Goblins_CACO_Patch.esp
CC-Nix-Hound_CACO_Patch.esp
CC-TheCause_CACO_Patch.esp
CuttingRoomFloor_CACO_Patch.esp
RelationshipDialogueOverhaul_CACO_Patch.esp
CACO_Wintersun.esp
SDA Wintersun Patch.esp
CACO_SunHelm.esp
Pilgrim_CACO_Patch.esp
CACO_Growl_Patch.esp
S3DTrees - CACO Patch.esp
KvSweets_CACO.esp
PathOfSorcery.esp
Vokrii - Minimalistic Perks of Skyrim.esp
Vokrii - Trade & Barter Patch.esp
Mysticism - Vokrii Compatibility Patch.esp
Vokrii - WACCF Patch.esp
Vokrii - Bruma Patch.esp
Apocalypse - Vokrii Compatibility Patch.esp
Odin - Vokrii Compatibility Patch.esp
PilgrimVokriiMysticismPatch.esp
Ordinator - Perks of Skyrim.esp
MysticOrdinator.esp
Apocalypse - Ordinator Compatibility Patch.esp
ReClassified.esp
CACO_Ordinator_Patch.esp
Ordinator - Combat Styles.esp
PilgrimOrdinatorPatch.esp
Ordinator_WACCF_Patch.esp
CWIOrdinatorPatchSSE.esp
Ordinator - Beyond Skyrim Bruma Patch.esp
ReClass_ApocalypsePatch.esp
ReClass_PilgrimPatch.esp
ReClassified_MysticismPatch.esp
Odin - Ordinator Compatibility Patch.esp
Vokriinator Black.esp
FZmx - DAC - Vokriinator.esp
Vokriinator Black - Apocalypse patch.esp
Vokriinator Black - CACO patch.esp
Sexcraft Vokriinator Patch Redux.esp
Sacrosanct - Vampires of Skyrim.esp
RaceCompatibility-Sacrosanct-Patch.esp
Sacrosanct_CACO_Patch.esp
Better Vampires.esp
Better Vampire Lords.esp
Add Sacrosanct Spells to BV.esp
BVandRoyalBloodline_Patch.esp
nwsFollowerFramework.esp
SDA NFF Patch.esp
nwsFF_NTMD_Apocalypse.esp
Lux.esp
New Merge 3.esp
Lux - 3DNPC patch.esp
Lux - Legacy of the Dragonborn patch.esp
Lux - Palaces Castles Enhanced patch.esp
Lux - Blue Palace Terrace patch 3.esp
Lux - JK's Blue Palace patch.esp
Lux - JK's Blue Palace Terrace patch.esp
Lux - USSEP patch.esp
Lux - SLaWF patch.esp
Lux - No grass in caves patch.esp
Lux - Forgotten Seasons.esp
Lux - Embers XD patch.esp
Lux - MEZF Vanilla Patch.esp
Lux - Nchuanthumz Dwarven Home patch.esp
Lux - Goldbrand CC.esp
Lux - Goblins CC.esp
Lux - Vigil Enforcer CC.esp
Lux - JK's Bards College patch.esp
AcousticTemplateFixes_Lux.esp
Lux - Bittercup Patch.esp
Lux - Dead Mans Dread Patch.esp
Lux - Shadowfoot Sanctum patch.esp
Lux - Bloodchill Manor patch.esp
JKs BPT - LOTD + Lux patch.esp
Lux - CC Fish patch.esp
Lux - Cuting Room Floor.esp
Lux - Dawnfang CC.esp
Lux - Elite Crossbows.esp
Lux - Farmer patch.esp
Lux - Ghosts of the Tribunal CC.esp
Lux - Hendraheim patch.esp
Lux - Necrohouse patch.esp
Lux - Pets of Skyrim CC.esp
Lux - Saints and Seducers patch.esp
Lux - Staff of Hasedoki CC.esp
Lux - The Cause patch.esp
Lux - Tundra Homestead patch.esp
Lux - Umbra CC.esp
Lux - Skyrim Sewers.esp
Lux - JK's Dragonsreach patch.esp
Lux - JK's Skyrim.esp
Lux - Castle Volkihar Rebuilt patch.esp
open cities skyrim.esp
JKs Skyrim_Open Cities_Patch.esp
LuxMerged.esp
ocs + lotd6 patch.esp
PCE - Open Cities Patch.esp
SoS_OpenCities_Patch.esp
ocs + skyrim sewers.esp
CWIOpenCitiesSEPatch.esp
ocs + dfos comp patch.esp
Phenderix OCS Patch.esp
ocs + gray cowl returns patch.esp
OpenCitiesSkyrim_CACO_Patch.esp
ocs + bittercup patch.esp
ocs + dawnfang patch.esp
DynDOLOD.esp
Occlusion.esp

**Comment by Fikthenig** [comment]
I'm having the same issue to I'm not sure why. I views this many times before and is issues never popped up. I'm on 1.5.97 and this same thing popped up for me including base game file such as Skyrim.esp and Dawnguard.esp

**Comment by Fikthenig** [comment]
Figured it out!!! It was when I updated Morenastycritters. Disable that mod before opening easynpc

**Comment by focustense** [comment]
This issue has been discussed many times in the Discord chat and isn't a bug in EasyNPC. It's arguably a bug in the version of Mutagen from about 3 years ago, but Mutagen was just following the actual spec, whereas the authors of certain mods are using a form/record combination that is technically permissible in game but doesn't conform strictly to the spec.

Mutagen probably loosened the requirement at some point, but given the nature of the mods generally implicated, I have no plans to test it on a dev version and don't really want the issue discussed on GitHub either. It's very easy to find on the Discord server by just searching for "BOD2".
