### ISSUE TITLE
EasyNPC SOmething went wrong error after building

### ISSUE THREAD

**Issue by Crow-dot** [focustense/easymod#208]
Hello there!

I would like to ask for assistance, EasyNPC gives me the "Something went wrong" message after trying to build npcs.
here is my log: https://pub.microbin.eu/upload/ape-cat-raven

Thank you for your time in advance!

**Comment by focustense** [comment]
It says you've got the ESP open in another app.

```
The process cannot access the file 'F:\***\Vortex Staging Folder\Skyrimse\NPC Merge 2024-11-24\NPC Appearances Merged0.esp' because it is being used by another process.
```

You need to close it in xEdit or whatever else you have open. Also, the message suggests you're trying to build to an output directory that already exists - it's not supposed to even allow that, but if it is allowing that then please build to a new/empty directory instead.
