### ISSUE TITLE
Crash at Start of Merged Plugin Creation

### ISSUE THREAD

**Issue by einmyra** [focustense/easymod#39]
Program runs fine and reports no build errors up until actually building the merged plugin and then crashes immediately.

Log: https://pastebin.com/YcncETBU

I've double checked my settings, limited my mod list and can start the game without an issue. I also tried reinstalling EasyNPC from scratch.

**Comment by focustense** [comment]
This is issue #31, resolved in build 0.8.3. You probably still have version 0.8.1 that was posted on Nexus yesterday - it took a while to get un-quarantined.

If you update to 0.8.3, you should be fine. If you're already using 0.8.3, please reopen.
