### ISSUE TITLE
Crashing When Attempting to Build on 0.8.6

### ISSUE THREAD

**Issue by AlgonquinLlama** [focustense/easymod#48]
I get this error (https://pastebin.com/cyFZN6Bf [This is the event viewer log]) when attempting to build. The app is saying it can't find a part of the path to the Pandorable's Males folder. Full log file below.

[Log_20210719_223021_7463781.txt](https://github.com/focustense/easymod/files/6845482/Log_20210719_223021_7463781.txt)

**Comment by focustense** [comment]
The error (snipped) is:

```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\pjpoi\AppData\Roaming\Vortex\skyrimse\mods\Pandorable's NPCs - Males SE-42043-1-1-1606269312'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.EnumerateFiles(String path, String searchPattern, SearchOption searchOption)
   at Focus.Apps.EasyNpc.Build.MergedFolder.<>c__1`1.<Build>b__1_9(String modPath)
```

Can we start by checking whether or not this directory does actually exist on your machine? If it doesn't, then the next step will be to find out where the path is coming from, but let's first eliminate the obvious.

**Comment by AlgonquinLlama** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/87685390/126263096-9955435f-7a3a-411c-bf85-4a25d6d127a7.png)
 Unless I'm missing something that should be it

**Comment by focustense** [comment]
I do see a difference there - the one in your screenshot ends with a ".1", whereas the path it's looking for does not.

If there's nothing too private in there, would you be alright with linking/attaching your Vortex bootstrap file? You can find it at `%TEMP%\easynpc-vortex-bootstrap.json`. It sounds like EasyNPC is getting bad info from the Vortex Extension, which might be getting bad info from Vortex itself. That file will help narrow it down.

**Comment by AlgonquinLlama** [comment]
Github wont let me drop and drag the file in, is there another way to link it?

**Comment by AlgonquinLlama** [comment]
https://pastebin.com/VhM5xvL5 
Hopefully that's what you mean

**Comment by AlgonquinLlama** [comment]
Edit: This is the txt format conversion if it helps at all. https://pastebin.com/BUp5iTXt.

**Comment by focustense** [comment]
Yes, that's what I meant - thanks.

This is an odd one, as the bootstrap file also has the ".1". I'm not sure why it's getting stripped off like that.

I can think of two possibilities here:

1. There's a bug somewhere that's treating the `.1` as a file extension and dropping it.
2. One or more NPCs in your profile are pointing to a mod with the name that is missing `.1`. I.e. they point to a mod that doesn't currently exist.

While the first option is definitely possible, I would have expected it to be reported much earlier if that were the case. So for the moment I think we should dig into the second possibility.

Is it possible that you originally had a non-variant of this mod (Pandorable's NPCs - Males), without the `.1`, ran EasyNPC on that earlier version, and later reinstalled the mod or changed something? That could account for why NPCs might be pointing to a non-existent mod (if it used to exist).

Another thing to check is in the app itself. Use the filter to find all NPCs with the Pandorable's NPCs - Males plugin selected as the face, and note what you see in the previews at the bottom. Do you see the green check on a mod that has "mod not installed" showing in red text, or does everything look OK for those NPCs?

**Comment by focustense** [comment]
If it does turn out to be option 2 above, it occurs to me that the app probably should not allow a build to start at all with invalid mod selections, since it is pretty much always going to crash like that. (Just making a not-so-mental note)

**Comment by AlgonquinLlama** [comment]
I did reinstall it earlier trying to figure out why I was getting an error with pandorable's males NPCs (I had just misused the app) and deleted the original files to get rid of the multiples of pandorable's male npcs it shows beneath previews.

**Comment by AlgonquinLlama** [comment]
There weren't any with a check and the red text saying the mod wasn't installed under pandorable's males.

**Comment by AlgonquinLlama** [comment]
Update: For whatever reason (went back through and still couldn't find a warning) deselecting all the pandorable's npc males, restarting the app and reselecting them has gotten the app past the crash.

**Comment by focustense** [comment]
I think some of them ended up pointing to the version that got deleted. That's more or less what the log is saying. It won't look for any mod folders that aren't referenced in some way by your profile.

If you can't find them using the filters, you could export and attach a profile, and I can take a look to see where it's being referenced. Since it's not in your Vortex bootstrap, I think that is the only place it can be.

**Comment by AlgonquinLlama** [comment]
Really appreciate the help man
