### ISSUE TITLE
Custom body carry-over

### ISSUE THREAD

**Issue by focustense** [focustense/easymod#7]
While it's going to be far better for compatibility to _not_ carry over custom bodies, in the spirit of allowing users to be in full control, this should still be allowed.

In principle, not very difficult - copy the `WNAM` and make it standalone like we do with `HDPTs`.

Questions abound on how best to expose the feature:

- Global override?
- Per mod/plugin?
- Per NPC?
- Do we need body previews?
- Do we need to warn (e.g. about armor clipping, physics issues)?
- Use as automatic fallback for wig conversion (wigs also use WNAM)?
- Only if the body would otherwise be vanilla (i.e. load order doesn't include body mods)?

And probably more. Most of the work will go into the UI design and mind-reading logic, rather than the record-copying itself.

**Comment by focustense** [comment]
In personal testing, I observed some serious texture discrepancies that made a few custom-bodied NPCs look bad. I guess they are using face tints or possibly face texture sets to match with custom body textures. What I'd like to do is see if there is a way to use default meshes, but still preserve any custom textures - however, this may not be workable, because the textures may not be compatible with default meshes (e.g. CBBE vs. UNP). Could also try messing with the face tints, but first need a much clearer understanding of how everything matches up.

In any case, what it comes down to is that this is an important fast-follow feature, because some overhauls aren't quite usable without the ability to carry over custom bodies. This probably needs to be configurable on a per-mod basis, possibly per-NPC but I hope not because that would add a lot of user complexity.

**Comment by llyarc** [comment]
It's the same problem as this https://github.com/focustense/FocusPatchers/issues/2 In skyrim, the face skin depends on the facegen. it is not possible to simply remove the Custom body without editing the facegen. But I still want you to keep this feature.Here is a sseedit script that will do it correctly, I hope it will help you https://www.nexusmods.com/skyrimspecialedition/mods/36042 NPC De-Standaloner

**Comment by focustense** [comment]
Thanks for the link. I'm not sure I'd say, without reservation, that what the script does is "correct", as what it will actually do is try to remove all of the custom face/head textures and point them back at vanilla, or whatever is replacing vanilla. To me, that would be missing the point of an "overhaul manager" and for the purposes of EasyNPC, most of the time it would not be the desired behavior - better to actually merge the custom body.

For the standalone Synthesis patcher it could make sense, as that patcher is really just about removing things that are there.

**Comment by focustense** [comment]
I guess I may as well take a second to elaborate on what's actually going to be available in EasyNPC, for anyone else who ends up at this issue.

Version 0.9 will preserve the body replacer in its entirety, because I made the wrong decision back in 0.1. It's not always the right choice, but it's likely to be the best choice most of the time, even though I don't like what it does to armors/outfits/etc.

Sometime between version 0.9 and 1.0, this will turn into a per-mod setting. Whenever we detect that an NPC mod uses body replacers, there will be the choice to do any of the following:

1. Maintain the custom body (default)
2. Remove the custom body, but preserve face textures (current behavior)
3. Remove the custom body and _remove_ custom face textures (similar "de-standaloner" behavior)
4. Attempt to merge the custom textures with the default body (requires the overhaul to use a compatible body type, CBBE and UNP are not compatible and I'm not sure if there's a way to determine that automatically - possibly through the bone names? - but initially you'd have to choose this option explicitly and know what you're doing)

The reason for doing this on a mod level, rather than NPC level, is that I'm assuming that 99% of the time users are trying to get as close as possible to what the overhaul shows in its screenshots, fomods, etc., otherwise they would just pick a different mod entirely for that NPC. Given that goal, there is going to be one choice that works best for the entire mod. If it's a compatible body type, for example, then it's option 4; otherwise it's likely option 1, with options 2 and 3 being for the advanced users who don't mind experimenting to see what works.
