### ISSUE TITLE
Massive Master List - Can't scroll to Build button

### ISSUE THREAD

**Issue by MatteoGatto95** [focustense/easymod#77]
Maybe this is stupid, but I couldn't find any way to scroll down my immense master list at the build page to click on the build button. I am leaving an image below to show the issue.

![image](https://user-images.githubusercontent.com/62948242/126906101-81aaa3ed-e324-493b-928d-2b0b0cffe522.png)

**Comment by focustense** [comment]
Looks like I forgot to add a scroll viewer and didn't anticipate the master list being so large.

It's a messy workaround, but until the next fix goes out, you can click on one of the master dependencies (any of them, doesn't matter which), hit the Tab key, and press Enter to start the build.

**Comment by MatteoGatto95** [comment]
Top! Thank you!
