### ISSUE TITLE
Body appearance data part of "Default Source" plugin

### ISSUE THREAD

**Issue by Yuheeeng** [focustense/easymod#79]
The description of "Default Source" implies that it only includes non-appearance data, but that's not the case. The body appearance of the NPC being edited would come from the "Default Source" instead of the "Face Source", which means if the user has selected two different plugins as the "Default Source" and the "Face Source", the NPC they edit would have an unexpected body appearance.

Edit: Looks like the issue was already mentioned in "Custom body carry-over #7".

**Comment by focustense** [comment]
As of 0.9, skins are inherited from the face source, so it effectively does cover all appearances now.
