### ISSUE TITLE
"Something Went Wrong" Bug

### ISSUE THREAD

**Issue by rf7033nk** [focustense/easymod#91]
[Log_20210813_200446_6134996.txt](https://github.com/focustense/easymod/files/6985748/Log_20210813_200446_6134996.txt)

This was my first time using the program, through MO2

**Comment by focustense** [comment]
You're using a very old version of the app - this is bug #31 and was fixed quite some time ago.

Please update.

**Comment by rf7033nk** [comment]
Oof, my bad. Turns out I downloaded the update but never installed it.
Thank you for the quick response!
