### ISSUE TITLE
Mismatched Face mod/face plugin error for one specific NPC

### ISSUE THREAD

**Issue by rf7033nk** [focustense/easymod#96]
Apologies if this has been covered before, but I've run into an issue I haven't been able to figure out.

When I check the build for errors before making the merge, one of the warnings is telling me that Sorine from the Dawnguard DLC has a [mismatched face mod and face plugin between Pandorable's Dawnguard NPCs and The Ordinary Women respectively](https://postimg.cc/GHPQ2FqS). The solutions are to reload the plugin that isn't loaded (in this case, Pandorable's Dawnguard NPCs), or choose another option that has consistent facegen data. But despite having Pandorable's Dawnguard NPCs loaded, it doesn't appear that EasyNPC is detecting it. [The plugin isn't showing in the profile tab when I select Sorine's name, even with the mugshot present](https://postimg.cc/cgVmKTpP). I have all of Pandorable's NPC replacers installed and enabled (with the exception of Lethal Ladies), and after checking several times, this is the only Pandorable mod that I've been getting a warning for, so I'm not sure how to fix this.

(I checked all the other Dawnguard NPCs edited by Pandorable's plugin as well, and Sorine is the only NPC this is happening to, which is even more bizarre.)

Admittedly, before this program was developed, I had issues getting TOW to play nice with Pandorable's NPC replacers in the past, and I tried to amend this the old-fashioned way. I opened them in xEdit and deleted the NPC records that I didn't want, on top of making sure TOW was directly below every Pandorable plugin in my load order. When I got this error, I went and reinstalled both TOW and Pandorable's Dawnguard NPCs, but I'm still getting the same error. Any help you could throw my way would be greatly appreciated!

**Comment by focustense** [comment]
See if this is still affecting you in v0.9.1. Explicit mod selections are rarely used anymore and it won't likely use a mod you don't have. If it does, you should be able to go to the NPC and change it easily enough.

If the new version still isn't working for you, please reopen.

**Comment by rf7033nk** [comment]
> 
> 
> See if this is still affecting you in v0.9.1. Explicit mod selections are rarely used anymore and it won't likely use a mod you don't have. If it does, you should be able to go to the NPC and change it easily enough.
> 
> If the new version still isn't working for you, please reopen.

Thanks for the reply and update!
Version 0.9.1 worked, although Pandorable's Dawnguard NPCs plugin still wasn't loading for Sorine. But when I checked the build for errors, [it gave me a different message than the first time](https://postimg.cc/FdnJLnmt). I didn't look at the solutions it provided, but that message was the very last one in the log.

I was able to build a merge successfully afterwards, but I have yet to test it.
